###
# Deploy website to GitHub Pages for each Pull Request,
# so we can preview the game online, before merging.
#
# Bot posts link to the website as a comment to Pull Request.
# See https://github.com/marketplace/actions/deploy-pr-preview
###
name: Deploy PR previews

# Deploy website to Github Pages when pull request is:
# opened, reopened, and pushed ("synchronize")
# Also delete the pull request privew, when it is closed.
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

concurrency: preview-${{ github.ref }}

# Use https://github.com/marketplace/actions/deploy-pr-previe
# To deploy website preview to Github Pages for each Pull Request
jobs:
  deploy-preview:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: .
          preview-branch: gh-pages
          umbrella-dir: pr-preview
          action: auto
